Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,11 +2,11 @@ version: 2.1
 jobs:
   build:
     docker:
-      - image: fr3akyphantom/droid-runner:latest
+      - image: fr3akyphantom/droid-builder:latest
         auth:
           username: "$DOCKER_USERNAME"
           password: "$DOCKERHUB_TOKEN"
-      - image: fr3akyphantom/droid-builder-beta:focal
+      - image: fr3akyphantom/droid-runner:latest
         auth:
           username: "$DOCKER_USERNAME"
           password: "$DOCKERHUB_TOKEN"
@@ -27,14 +27,15 @@ jobs:
             git config --global -l
       - run:
           name: Pre-Initialize
-          command: df -hlT
+          command: |
+            df -hlT
       - setup_remote_docker:
           version: 19.03.13
       - run:
           name: Post-Initialize
           command: |
-            echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKER_USERNAME --password-stdin
-            docker pull sickcodes/docker-osx:latest
+            df -hlT
+            echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKER_USERNAME --password-stdin || echo "Docker command error, still"
 workflows:
   version: 2
   workstation:
